In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
 
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


array([[ 0.15530413,  0.80249131],
       [ 0.13850413,  0.75828706],
       [-0.14067296,  1.06249989]])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [5]:
# Basic Math
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)


array([0.84147098, 0.90929743, 0.14112001])

In [6]:
 
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B



array([[19, 22],
       [43, 50]])

In [7]:
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()



np.float64(1.118033988749895)

In [8]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]



array([1, 3, 5])

In [9]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]


array([4, 5])

In [10]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]


array([4, 5])

In [11]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)
 
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))
 


array([1, 2, 3, 4])

In [12]:
# Stacking
np.vstack((a, b))
np.hstack((a, b))


array([1, 2, 3, 4])

In [13]:
a = np.array([1, 2, 3])
a + 5  # [6, 7, 8]


array([6, 7, 8])

In [14]:
# Save to a file
np.save('array.npy', arr)
 
# Load from a file
loaded_arr = np.load('array.npy')
